# MySQL DataSource Configuration
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3300/dummy
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: dev
  # Jwt Configuration
#  security:
#    generate:
#      jwt:
#        is-issuer
#server:
#  port: 8080