version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "dummy"
    ports:
      - "3300:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: